- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/addrepos.yml
    - include: tasks/packages.yml
    - include: tasks/groups.yml
    #- include: tasks/users.yml
    #- include: tasks/cron.yml
    